### ISSUE TITLE
Missing header and footer in Terms and condition and privacy policy page 

### ISSUE THREAD

**Issue by tannu610** [pranjay-poddar/Swasthify#127]
**Describe the Feature you want to end**

Header and footer is mission in the terms and condition and privacy policy page as its present in about us and other main pages.
**Expected behavior**

it should be present there as well i want to add  them assign me this 
**Screenshots (optional)**

**Additional context (optional )**

**Comment by tannu610** [comment]
@pranjay-poddar Please assign me this under the hacktoberfest.

**Comment by pranjay-poddar** [comment]
We are using third party in privacy policy and terms and conditions that can't be edited
