### ISSUE TITLE
Improve the Footer

### ISSUE THREAD

**Issue by SanskritiGupta05** [pranjay-poddar/Swasthify#134]
**Describe the Feature you want to end**
I would like to improve how the Footer looks and add some things to it.
* Copyright Statement
* made with love statement
* all rights reserved statement

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/77205923/197386838-9b87e641-cf25-49df-ae71-f12a9c5126b9.png)

**Additional context (optional )**
after doing this, I am willing to contribute more to this project.
**Please assign this issue to me @pranjay-poddar with the Hacktoberfest tag.**

**Comment by ergovind08** [comment]
hello can i help you to improve your footer page

**Comment by SanskritiGupta05** [comment]
Sure, but the maintainer needs to assign us first.

**Comment by SanskritiGupta05** [comment]
Please add the Hacktoberfest label to the issue @pranjay-poddar

**Comment by adityapund** [comment]
Hello @pranjay-poddar  I would like to improve your footer with
Copyright, made with love, all rights reserved, along with About us and follow us elements please assign me this issue.

**Comment by Raghuraj-source** [comment]
Can I improve website footer.
