### ISSUE TITLE
height of navbar is different in both Light and dark mode 

### ISSUE THREAD

**Issue by vardhan0604** [pranjay-poddar/Swasthify#58]
@pranjay-poddar  can you assign me this under hacktoberfest . i would like to fix this issue

**Comment by vardhan0604** [comment]
hey sorry to inform you that I ain't familiar with bootstrap so I won't be able to fix this issue.So please assign this to someone with the right skills.

**Comment by Liahus3003** [comment]
@pranjay-poddar Can I look into this as part of Hacktoberfest?

**Comment by Liahus3003** [comment]
Issue is fixed with this PR: https://github.com/pranjay-poddar/Swasthify/pull/62
