### ISSUE TITLE
Fix scrollbar issue on footer image animation

### ISSUE THREAD

**Issue by xxGizmoCodexx** [pranjay-poddar/Swasthify#64]
Hi @pranjay-poddar 
Amazing project and effort!

I would like to fix the animation on the footer image section causing scrollbar issues as shown in the video attached. I would like to fix this as part of my Hacktoberfest 2022 contribution

https://user-images.githubusercontent.com/16000608/193413238-cb5ebe1d-eb6a-42b3-a68f-261867b2afc2.mp4

**Comment by xxGizmoCodexx** [comment]
@pranjay-poddar 
Please see #66 for resolution of this

**Comment by pranjay-poddar** [comment]
@xxGizmoCodexx thanks man!
