### ISSUE TITLE
Fix overlapping login images on large displays

### ISSUE THREAD

**Issue by xxGizmoCodexx** [pranjay-poddar/Swasthify#65]
Hi @pranjay-poddar
Amazing project and effort!

I would like to fix the overlapping login images on large displays as shown in the video attached. This seems to be both in the Hospital and Patient login section.
I would like to fix this as part of my Hacktoberfest 2022 contribution

Hope this will help, thank you

https://user-images.githubusercontent.com/16000608/193413552-f4c6baab-d558-4c9e-a9ce-79b85487771a.mp4

**Comment by thexahmed00** [comment]
i would like to take this issue
