### ISSUE TITLE
Fix alignment issues in Patient dashboard screen

### ISSUE THREAD

**Issue by Liahus3003** [pranjay-poddar/Swasthify#71]
**Describe the bug**
Some of the features are not properly aligned and responsiveness behaviour isn't perfect

**Expected behavior**
Updated search filter with responsive behaviour

**Comment by thexahmed00** [comment]
where is java files and pom??

**Comment by thexahmed00** [comment]
spring boot configuration??

**Comment by thexahmed00** [comment]
@pranjay-poddar

**Comment by pranjay-poddar** [comment]
@thexahmed00 https://github.com/pranjay-poddar/Swasthify-Backend
