### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [pranjay-poddar/Swasthify#79]
**Describe the Feature you want to end**
A sticky navbar can be added to enhance the design. It would enable users to have access without having to scroll.

**Expected behavior**
It will be a fixed element in the page.
 
I would like to work on this issue under Hacktoberfest 2022.

**Comment by shahnewaztameem** [comment]
is this still open? Can you please assign me?

**Comment by kirtanchandak** [comment]
hey is anyone working, can I take this issue ?
