### ISSUE TITLE
Adding hover effect on navbar

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Swasthify#81]
Hey @pranjay-poddar I want to add hover effect on the navbar. Can you please assign me this issue. Thank you!

**Comment by pranjay-poddar** [comment]
Everything is mention in the readme

**Comment by sumitkr2000** [comment]
Sorry bro I didnt saw it, I have not learnt Angular so I will not be able to solve this issue. You can unassign me.

**Comment by Abhishek-Mallick** [comment]
I will like to work on this, please assign this to me

**Comment by sumitkr2000** [comment]
@pranjay-poddar assign it to @Abhishek-Mallick

**Comment by Abhishek-Mallick** [comment]
> @pranjay-poddar assign it to @Abhishek-Mallick

I'm having issues deploying it don't assign it to me

**Comment by pavankumarraju13** [comment]
can you please assign it to me?
