### ISSUE TITLE
Add interactive cards with better ui

### ISSUE THREAD

**Issue by duplixx** [pranjay-poddar/Swasthify#82]
I want to add good looking cards which can also be flipped for more info 
It will look great in webapp

**Comment by pranjay-poddar** [comment]
can you attach some video or screenshots to elaborate it also in which section would you like to enhance the UI?

**Comment by duplixx** [comment]
![image](https://user-images.githubusercontent.com/90516956/194115132-1737eff4-6c50-4217-9b8f-1f17cc2ec428.png)
cards like this in hero section

**Comment by pranjay-poddar** [comment]
Not getting your point by hero section, can you please explain more?

**Comment by duplixx** [comment]
![image](https://user-images.githubusercontent.com/90516956/194119965-93f82aca-4a47-4a4c-bc43-8eef6d40010b.png)
we can improve this section by these cards with dedicated gradient and hover effect

**Comment by heysaiyad** [comment]
Sir you give me a chance, I will make it very attractive Page.
