### ISSUE TITLE
Hover Effect

### ISSUE THREAD

**Issue by Rituraj-13** [pranjay-poddar/Swasthify#84]
**Describe the Feature you want to end**
I want to add Hover effect on the Header links.
![image](https://user-images.githubusercontent.com/90104572/194095899-8f0e583b-0599-429c-82fa-ded0aba9f6de.png)

**Expected behavior**
Whenever the cursor will be hovering over those links, it will make a hover effect & it will definitely improve the user experience.

**Screenshots (optional)**

**Additional context (optional )**

-------------------------------------------------------------------------------------------------------------------------------------------

**Hey, I want to contribute on this. Can you please assign me for this?**

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by shahnewaztameem** [comment]
assign me this issue please

**Comment by Aakash441** [comment]
I can see that the hover effect is not visible till now. If so, please assign me this.

**Comment by pranjay-poddar** [comment]
> I can see that the hover effect is not visible till now. If so, please assign me this.

It is visible, you can work for that in dark mode by opening new issue
