### ISSUE TITLE
Hover effect using CSS 

### ISSUE THREAD

**Issue by heyhimansh** [pranjay-poddar/Swasthify#86]
**Describe the Feature you want to end**
I want add CSS animation to the navigation bar so that while hovering on the navbar content text size increases.It provides a good UI. 

**Expected behavior**
https://heyhimansh.github.io/gitcheatsheet/    you can check this while hovering on these icons 
![Swasthify and 94 more pages - Personal 2 - Microsoft​ Edge 06-10-2022 13_32_54 (2)](https://user-images.githubusercontent.com/72097380/194254970-6730e336-b0d9-4694-9e09-986eaac374e4.png)

so,  assign this task to me and considered this for my HACKTOBERFEST-2022 PR.

Thank you!

**Comment by Purvesh77** [comment]
Hey @heyhimansh @shreyanshp25 I want to work on this task.
So can you assign me ? 
Thank You !
